# Generated by Django 3.0.2 on 2020-01-05 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_group_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=200)),
                ('hospital_address', models.CharField(max_length=200)),
                ('hospital_hospitalgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stratHealthApp.HospitalGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_address', models.CharField(blank=True, max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=200)),
                ('contact_position', models.CharField(blank=True, max_length=200)),
                ('contact_hospital_list', models.ManyToManyField(blank=True, to='stratHealthApp.Hospital')),
            ],
        ),
    ]
