# Generated by Django 3.0.2 on 2020-01-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratHealthApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_hospitalGroup',
            field=models.ManyToManyField(blank=True, to='stratHealthApp.Hospital'),
        ),
    ]
