# Generated by Django 3.0.2 on 2020-01-05 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stratHealthApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=200)),
                ('staff_startDate', models.DateField()),
                ('staff_position', models.CharField(max_length=200)),
                ('staff_salary', models.DecimalField(decimal_places=3, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='Procedures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_date', models.DateTimeField()),
                ('procedure_cost', models.DecimalField(decimal_places=3, max_digits=16)),
                ('procedure_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stratHealthApp.ProcedureCategory')),
                ('procedure_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stratHealthApp.Hospital')),
                ('procedure_staff', models.ManyToManyField(blank=True, to='stratHealthApp.Staff')),
            ],
        ),
    ]
