# Generated by Django 3.0.2 on 2020-01-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratHealthApp', '0002_procedurecategory_procedures_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedures',
            name='procedure_description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedures',
            name='procedure_name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
