# Generated by Django 3.0.2 on 2020-01-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratHealthApp', '0002_auto_20200103_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_jobTitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
