# Generated by Django 3.0.2 on 2020-01-06 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stratHealthApp', '0003_auto_20200106_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedures',
            name='procedure_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stratHealthApp.ProcedureCategory'),
        ),
        migrations.AlterField(
            model_name='procedures',
            name='procedure_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16),
        ),
        migrations.AlterField(
            model_name='procedures',
            name='procedure_description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_position',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_salary',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13),
        ),
    ]
