# Generated by Django 3.0.2 on 2020-01-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratHealthApp', '0003_auto_20200104_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(max_length=200),
        ),
    ]
