# Generated by Django 3.0.2 on 2020-01-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratHealthApp', '0004_auto_20200106_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedures',
            old_name='procedure_staff',
            new_name='procedure_staff_list',
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_hospital',
            field=models.ManyToManyField(blank=True, to='stratHealthApp.Hospital'),
        ),
    ]
