# Generated by Django 3.0.2 on 2020-01-06 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stratHealthApp', '0005_auto_20200106_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='staff_hospital',
            new_name='staff_hospital_list',
        ),
    ]
